config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'photographs/index'
  root to: "photographs#index"
  resources :photographs do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '車' },
    { id: 3, name: 'バイク' },
    { id: 4, name: '自転車' },
    { id: 5, name: '徒歩' },
    { id: 6, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :photograph
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photograph

  validates :content, presence: true
end

app/models/photograph.rb
class Photograph < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :category
  belongs_to :prefecture

  with_options presence: true do
    validates :title
    validates :category_id
    validates :prefecture_id
    validates :description
    validates :image
    validates :address
  end

  validates :category_id, numericality: { other_than: 1 }
  validates :prefecture_id, numericality: { other_than: 1 }

  def self.search(search)
    if search != ""
      Photograph.where('description LIKE(?)', "%#{search}%").
        or(where('title LIKE(?)', "%#{search}%"))
    else
      Photograph.all
    end
  end

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :photographs
  has_many :comments

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers.' }

  with_options presence: true do
    validates :nickname

    with_options format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'is invalid. Input full-width characters.' } do
      validates :last_name
      validates :first_name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [new, :destroy, :create, :edit]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to photograph_path(@comment.photograph)
    else
      @photograph = @comment.photograph
      @comments = @photograph.comments
      render "photographs/show"
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, photograph_id: params[:photograph_id])
  end
end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :destroy, :new]
  before_action :set_photograph, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @photographs = Photograph.all.order(created_at: :desc)
  end

  def new
    @photograph = Photograph.new
  end

  def create
    @photograph = Photograph.new(photograph_params)
    if @photograph.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comment = Comment.new
    @comments = @photograph.comments.includes(:user)
  end

  def search
    @photographs = Photograph.search(params[:keyword])
  end

  def edit
    unless user_signed_in? && current_user.id == @photograph.user_id
      redirect_to action: :index
    end
  end

  def update
    photograph = Photograph.find(params[:id])
    if photograph.update(photograph_params)
      redirect_to photograph_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    photograph = Photograph.find(params[:id])
    photograph.destroy
    redirect_to root_path
  end

  private

  def photograph_params
    params.require(:photograph).permit(:title, :category_id, :prefecture_id, :description, :image, :address, :latitude, :longitude).merge(user_id: current_user.id)
  end

  def set_photograph
    @photograph = Photograph.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photographs_helper.rb
module PhotographsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DriveToPhotograph</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("3.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
              <%= link_to "New Photo", new_photograph_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">I wish all drivers safety Goodluck.</p>
    </footer>
  </body>
</html>

app/views/pages/service.html.erb
<main class="main">
  <div class="inner">

    <div class="car_image">
        <%= image_tag "s-879724908.png", class:"car_image_back" %>
          <div class="service_title">
            このアプリケーションは皆様の愛車と風景を多くの人に見てほしいという思いから作成しました！
              <div class="service_title_sub">
                もちろん愛車を持たれない方も普段の散歩道で見かけた風景を投稿していただけるなら、「新規登録」を宜しくお願いします。
              </div>
              <h2 class="service_body">
                -使い方-
              </h2>
              <div class='select-reason-contents'>
                <ul class='reason-lists'>
                  <li class='list'>
                    <%= image_tag "intro01.jpg", class:"list-pict" %>
                    <span class='reason-list-number'>1</span>
                    <h3 class='reason-list-text'>
                      一覧で投稿を閲覧
                    </h3>
                    <p class='reason-list-description'>
                      写真をクリックで詳細を確認できます。
                      マイページでも自身の投稿が見れます。
                    </p>
                  </li>
                  <li class='list'>
                    <%= image_tag "intro02.png", class:"list-pict" %>
                    <span class='reason-list-number'>2</span>
                    <h3 class='reason-list-text'>
                      新規で写真を投稿
                    </h3>
                    <p class='reason-list-description'>
                      写真と幾つかの入力で投稿できます。
                      撮影地点は場所でも国道○○線でも。
                    </p>
                  </li>
                  <li class='list'>
                    <%= image_tag "intro03.jpg", class:"list-pict" %>
                    <span class='reason-list-number'>3</span>
                    <h3 class='reason-list-text'>
                      グーグルマップで位置確認
                    </h3>
                    <p class='reason-list-description'>
                      具体的な位置を見ることができます。
                      もし自らが行く機会があってもイメージしやすい。
                    </p>
                  </li>
                </ul>
              </div>
              <h2 class="service_body">
                -利用規約-
              </h2>
              <li class="service_body_rule">
                <p class='reason-list-description'>
                  1.ユーザーは自己の責任において本サービスのユーザーIDおよびパスワードを適切に管理するものとします。
                </p>
                <p class='reason-list-description'>
                  2.ユーザーIDおよびパスワードを第三者に譲渡または貸与しもしくは第三者と共用することはできません。
                </p>
                <p class='reason-list-description'>
                  3.法令または公序良俗に違反する行為は禁止です。
                </p>
                <p class='reason-list-description'>
                  4.ナンバープレートや自分自身が写っているなどの個人の特定できてしまう写真の投稿は禁止です。
                </p>
                <p class='reason-list-description'>
                  5.本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為は禁止です。
                </p>
                <p class='reason-list-description'>
                  6.ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。
                </p>
                <p class='reason-list-description'>
                  7.その他，不適切と判断する行為は禁止とさせていただきます。
                </p>
              </li>
          </div>
    </div>
  </div>
</main>

app/views/photographs/_form.html.erb
<%= form_with model: photograph, local: true do |f|%>
  <div class="field">

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <div id="previews"></div>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category"}) %>
  </div>

  <div class="field">
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
  </div>

  <div class="field">
    <%= f.label :description, "物語" %><br />
    <%= f.text_area :description, placeholder: "写真を撮った時の思い出と道のりを入力してください", class: :form__text %>
  </div>

  <%= form_with(model: @photograph, local: true, class: "mt-4 form-column-width") do |f| %>

  <div class="field">
    <%= f.label :address, "撮影地点", class: "form-label fw-bold"%><br />
    <%= f.text_field :address, autofocus: true,placeholder: "場所を入力してください", class: "form-control" %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit (@photograph.new_record? ? "投稿する" : "更新する"), class: "btn btn-primary mb-4" %>
  </div>
<% end %>

app/views/photographs/_photograph.html.erb
<% if user_signed_in? %>
<div class="card">
  <%= link_to image_tag(photograph.image, class: :card__img ), photograph_path(photograph.id) %>
  <div class="card__body">
    <%= link_to photograph.title, photograph_path(photograph.id), class: :card__title, method: :get %>
    <%= link_to "by #{photograph.user.nickname}",user_path(photograph.user.id), class: :card__user %>
  </div>
</div>
<% end %>

app/views/photographs/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: { photograph: @photograph } %>
    </div>
  </div>
</div>

app/views/photographs/index.html.erb
<main class="main">
  <div class="inner">

    <% if user_signed_in? %>
      <div class="greeting">
        <%= "ようこそ、" %>
        <%= link_to "Mr.#{current_user.nickname}", user_path(current_user), class: :greeting__link %>
      </div>
      <div class = search>
      <%= form_with(url: search_photographs_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
      </div>
    <div class="card__wrapper">
      <%= render partial: 'photograph', collection: @photographs %>
    </div>
    <% else %>
      <div class="car_image">
        <%= image_tag "s-879724908.png", class:"car_image_back" %>
          <div class="top_title">
            <h1>ようこそ !</h1>
            <h1>Drive to Photograph へ</h1>
              <div class="top_title_sub">
                貴方の愛車と風景をともに楽しんでいきましょう！
              </div>
            <div class="service">
              -このアプリのサービスはこちらからご参照をお願いします-
            </div>
            <div class="service_btn">
              <%= link_to 'Service', page_path('service'), class: :nav__btn %>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</main>

app/views/photographs/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">写真投稿</h2>
        <%= render partial: "form", locals: { photograph: @photograph } %>
    </div>
  </div>
</div>

app/views/photographs/search.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= "ようこそ、" %>
        <%= link_to "Mr.#{current_user.nickname}", user_path(current_user), class: :greeting__link %>
      </div>
      <div class = search>
        <%= form_with(url: search_photographs_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </div>
      <div class="card__wrapper">
        <% @photographs.each do |photograph| %>
          <%= render partial: "photograph", locals: { photograph: photograph } %>
        <% end %>
      </div>
    <% end %>
  </div>
</main>

app/views/photographs/show.html.erb
<main class="main">
  <div class="inner">
    <div class="photograph__wrapper">
      <p class="photograph__hedding">
        <%= @photograph.title %>
      </p>
      <%= link_to "by #{@photograph.user.nickname}", user_path(@photograph.user), class: :photograph__user %>

      <% if user_signed_in? && current_user.id == @photograph.user_id %>
        <div class="photograph__manage">
          <%= link_to "編集する", edit_photograph_path(@photograph), class: :photograph__btn %>
          <%= link_to "削除する", photograph_path(@photograph), class: :photograph__btn, data: { turbo_method: :delete } %>
        </div>
      <% end %>

      <div class="photograph__image">
        <%= image_tag @photograph.image %>
      </div>
      <div class="photograph__body">
        <div class="photograph__detail">
          <p class="detail__title">-車種-</p>
          <p class="detail__message">
            <%= @photograph.category.name %>
          </p>
        </div>
        <div class="photograph__detail">
          <p class="detail__title">-都道府県-</p>
          <p class="detail__message">
            <%= @photograph.prefecture.name %>
          </p>
        </div>
        <div class="photograph__detail">
          <p class="detail__title">-思い出語り-</p>
          <p class="detail__message">
            <%= @photograph.description %>
          </p>
        </div>
      </div>
        <div class="photograph__detail">
          <p class="detail__title">-撮影場所-</p>
        </div>
        <script type="text/javascript">
          function initMap() {
            var test = {lat: <%= @photograph.latitude %>, lng: <%= @photograph.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 15, 
                      center: test
                      });
            var transitLayer = new google.maps.TransitLayer();
            transitLayer.setMap(map);
            var contentString = '住所：<%= @photograph.address %>';
            var infowindow = new google.maps.InfoWindow({
              content: contentString
            });
            var marker = new google.maps.Marker({
                          position:test,
                          map: map,
                          title: contentString
                        });
            marker.addListener('click', function() {
              infowindow.open(map, marker);
            });
          }
        </script>
        <script async defer
                  src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
        </script>
        <style type="text/css">
          #map { height: 500px;
                margin-left: 150px;
                width: 70%;}
        </style>
        <div id="map"></div>
      <div class="photograph__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@photograph, @comment],local: true do |f|%>
            <div class="field">
              <%= f.label :content, "-コメント-" %><br />
              <%= f.text_field :content %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% else %>
          <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です。 ※※※</p></strong>
        <% end %>
        <ul class="comments_lists">
          <% if @comments %>
            <% @comments.each do |comment| %>
              <li class="comments_list">
                <%= comment.content %>
                <%= link_to "(#{comment.user.nickname})", user_path(comment.user.id), class: :comment_user %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さん"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">ニックネーム</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col3">メールアドレス</th>
            <td class="table__col4"><%= @user.email %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの投稿一覧"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'photographs/photograph', collection: @user.photographs %>
      </div>
    </div>
  </div>
</div>